### ISSUE TITLE
Linux content manager caching issue

### ISSUE THREAD

**Issue by RUSshy** [tlgkccampbell/ultraviolet#102]
If i load 2 times the same shader, then it crash with:

```	   
_effect  = _assets.manager.Load<Effect>("effects/point_light.vert");


Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'Ultraviolet.OpenGL.Graphics.ShaderSource' to type 'Ultraviolet.Graphics.Effect'.
   at Ultraviolet.Content.ContentManager.Load[TOutput](String asset, Boolean cache, Boolean fromsln)


``` 

It only happens on linux, i didn't have this issue on windows

**Comment by tlgkccampbell** [comment]
It's strange that this is only happening on Linux... are you loading any other effects? Do they share any shaders between them?

**Comment by RUSshy** [comment]
I retested today and yes this only happen in linux

In macOS and Windows it works fine

**Comment by tlgkccampbell** [comment]
If you can send me a minimal program which reproduces this bug on Linux, I can take a look at fixing it.

**Comment by RUSshy** [comment]
Is there a way to load effect from string content ?

**Comment by tlgkccampbell** [comment]
Not easily, though I could probably add a few methods which make it possible without too much work. What's your use case?

**Comment by RUSshy** [comment]
it is to workaround the issue, because i can't work on the game when im on linux :( i tried to fix it myself but without success

**Comment by RUSshy** [comment]
I don't know what i exactly did but i can't reproduce the issue

Maybe i updated .net core or something, i'm not sure, but what's sure is i updated lot of packages

I will reopen if issue happen again
