### ISSUE TITLE
ImGui rendering issue

### ISSUE THREAD

**Issue by GiecuMan** [tlgkccampbell/ultraviolet#110]
Rendering seems to be done in wrong order and outside of window area. [How it looks like.](https://i.imgur.com/mHO2yuj.png)
Happens on all of my windows 10 machines.

**Comment by tlgkccampbell** [comment]
I might have some spare time this weekend to look into this. Can you post the code which is responsible for drawing that window?

**Comment by tlgkccampbell** [comment]
I was able to reproduce this issue. The ImGui renderer wasn't properly enabling the scissor test. This will be fixed in the next release.
