### ISSUE TITLE
Visual Studio project templates

### ISSUE THREAD

**Issue by simoneddeland** [tlgkccampbell/ultraviolet#115]
Is it possible to create project templates that can be distributed via NuGet or some other platform to get a new project up and running, i.e. up to the point that you reach at the end on this page https://github.com/tlgkccampbell/ultraviolet/wiki/Getting-Started-on-Windows . It would probably make it easyer for beginners to try Ultraviolet out.

**Comment by tlgkccampbell** [comment]
We used to have these, but I deprecated them when I dropped the installer and switched to NuGet packages -- they didn't feel like they were worth the effort to maintain. If there's an easier way to distribute them, then that might be worth doing (I don't think you can do it through NuGet, but maybe I'm wrong?). I've thought about making Yeoman templates, for example -- those would have the advantage of working with Visual Studio Code. But it's something I'd have to give some thought to.

**Comment by tlgkccampbell** [comment]
This has been addressed with the addition of `dotnet new` templates, as described here: https://github.com/tlgkccampbell/ultraviolet/wiki/Getting-Started-with-.NET-Core-3.1
