### ISSUE TITLE
Anti-Aliasing DrawPrimitives

### ISSUE THREAD

**Issue by viniciusjarina** [tlgkccampbell/ultraviolet#116]
How use Ultraviolet to Draw Primitives using Anti-Alias

MG seems is not implemented for DesktopGL https://github.com/MonoGame/MonoGame/issues/6199

Thank you very much, and good job, Ultraviolet seems like a great replacement for MG

**Comment by tlgkccampbell** [comment]
You can enable MSAA in Ultraviolet by setting `MultiSampleBuffers` to 1 and `MultiSampleSamples` to an appropriate value (such as 2 or 4) on your `OpenGLUltravioletConfiguration` object during context creation.
