### ISSUE TITLE
Docs reference link down

### ISSUE THREAD

**Issue by Sicilica** [tlgkccampbell/ultraviolet#117]
Presumably [this link](http://uv.twistedlogik.net/ultraviolet/reference/latest) should hold the most recent build of the docs (it's referenced on the wiki etc), but it redirects back to the GitHub project root.

**Comment by tlgkccampbell** [comment]
Thanks for reporting this issue. It turns out that I misconfigured my server during a recent migration. It should be fixed now, though it's possible that you'll need to clear the old 301 redirect from your browser's cache in order to stop being redirected to GitHub.
