### ISSUE TITLE
Freetype 2 nuget packages broken?

### ISSUE THREAD

**Issue by IceReaper** [tlgkccampbell/ultraviolet#123]
When using the Freetype 2 package, i get this warning upon building under .net Core 3.1:

```
Warning NU1701 : Package 'Ultraviolet.FreeType2.Native 2020.2.0.4055' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
```

Using an Android project, this results in a crash regarding the missing freetype natives.

I have my game project defined as netstandard2.0 library using Ultraviolet and Ultraviolet.FreeType2. Upon that i have the actual projects as netcoreapp3.1 for desktop and xamarin for android using the Shim Packages, plus a reference to the game project. This works perfectly under desktop with and without freetype (just the above warning) and under android as long as i do not use freetype2.

**Comment by tlgkccampbell** [comment]
This will be fixed in the next release.
