### ISSUE TITLE
Thread.CurrentThread.CurrentCulture.Name is empty on OSX

### ISSUE THREAD

**Issue by IceReaper** [tlgkccampbell/ultraviolet#124]
Tried to run my project under OSX using .net Core 3.1, resulting in a crash regarding the not empty check for the Culture Name. Im on the latest OSX. System is set to German except the ui language, which is set to english as i want the clock, numbers, currency for my region, but prefer to have english strings visible on my development machines.

![image](https://user-images.githubusercontent.com/1322277/76114744-173a4400-5fe7-11ea-9a0d-a04815034a67.png)

**Comment by tlgkccampbell** [comment]
This will be fixed in the next release.
