### ISSUE TITLE
Update Ultraviolet StyleSheets Language Support to newer Visual Studios.

### ISSUE THREAD

**Issue by Donaut** [tlgkccampbell/ultraviolet#126]
[Ultraviolet StyleSheets Language Support](https://tlgkccampbell.gallerycdn.vsassets.io/extensions/tlgkccampbell/ultraviolet-visualstudio-uvss/2.0/1533565416841/Ultraviolet.VisualStudio.Uvss.vsix )  The extension can not be installed on visual studio 2019. Is there a compatibility issue why can't you do that?:)

**Comment by tlgkccampbell** [comment]
I actually did most of the work to enable this a while back, but apparently forgot to ever upload it to the Marketplace. I've just corrected that; version 2.1, now in the Visual Studio Marketplace, supports 2019.
