### ISSUE TITLE
UVSS Extension installer is broken.

### ISSUE THREAD

**Issue by Donaut** [tlgkccampbell/ultraviolet#127]
When I tried to install the extension I got the following error.
![Error1](https://user-images.githubusercontent.com/30203762/87095505-22c1a400-c241-11ea-9bd0-f6c57c41803d.png)

The error present since the installer includes wrong versions for the **Microsoft.VisualStudio.Component.CoreEditor** library
I opened the .vsix file in Winrar and change the supported version from **_15.0.26208.0,16.0_** to _**15.0.26208.0,**_  in the following files(**manifest.json, extension.vsixmanifest, catalog.json**) this way I'm able to install the plugin in visual studio 2019.

**Comment by tlgkccampbell** [comment]
Thank you for following up on this. I've published 2.2 to the Marketplace, which should fix this issue. Can you verify that that version works for you?

**Comment by Donaut** [comment]
I checked the installer and now it's working fine.
