### ISSUE TITLE
Button CommandParameter complex types.

### ISSUE THREAD

**Issue by Donaut** [tlgkccampbell/ultraviolet#128]
![Screenshot_2](https://user-images.githubusercontent.com/30203762/87113094-c5901780-c26d-11ea-832e-654b9abcc14f.png)

Currently, I learning the CommandParameters everything works as expected but when I didn't use the __ToString()__ function the compiler will break. And I got an error with the following.

![Screenshot_3](https://user-images.githubusercontent.com/30203762/87113248-1e5fb000-c26e-11ea-9632-096d27514745.png)
![Screenshot_4](https://user-images.githubusercontent.com/30203762/87113230-156ede80-c26e-11ea-910d-40aebf5f6bac.png)

**Comment by tlgkccampbell** [comment]
This appears to be a bug in the expressions compiler. I think I've identified the issue, and I should have a fix out in the next day or so.

**Comment by tlgkccampbell** [comment]
Version 2020.7.0.4298 has been pushed to NuGet. Can you verify that this update fixes your issue?

**Comment by Donaut** [comment]
Thank you so much. It's working fine now. :1st_place_medal: :100:
