### ISSUE TITLE
Cannot ProcessWorkItems in custom timing logic.

### ISSUE THREAD

**Issue by fireball87** [tlgkccampbell/ultraviolet#134]
I had been trying to play with a custom timing logic recently again (though from a much different point than before, as I now am only just wanting to see if i can't figure out what is making my draws studder a bit with fixed framerates/vsync)  

It seems as if "syncContext.ProcessWorkItems();" is not accessible from the scope of a custom timing.

**Comment by tlgkccampbell** [comment]
Commit 730b718b179d651d43dcb3acee2998482d0c1da4 changes `ProcessSingleWorkItem()` and `ProcessWorkItems()` on `UltravioletSynchronizationContext` from `internal` to `public`.
