### ISSUE TITLE
FMOD support

### ISSUE THREAD

**Issue by vfrz** [tlgkccampbell/ultraviolet#137]
Hello,

I've tried to install the FMOD audio plugin nuget but I can't find the main plugin class (FMODAudioPlugin). And the nuget package is marked as deprecated.
Is FMOD still supported?
If not why? And may I propose to update it to v2?

FMOD is now free for commercial use if your revenue is <200k but BASS is not free.

Thanks for your work.

**Comment by tlgkccampbell** [comment]
The FMOD audio implementation was always kind of an experiment, one which I eventually did away with when I realized that the license terms didn't allow me to distribute fmod.dll alongside Ultraviolet. That remains true as far as I'm aware, but given the recent pricing changes, I agree that I should probably revisit this in the near future.

Longer term, I want to look into an implementation based on OpenAL Soft, which has no cost. If I can make that work on all supported platforms, it will probably replace BASS as the default implementation.

**Comment by tlgkccampbell** [comment]
I've pushed a new release to NuGet which includes the `Ultraviolet.FMOD` package, and I've made sure the package is no longer marked as deprecated. You should be able to find `FMODAudioPlugin` there. Please remember that, for licensing reasons, you'll need to provide your own copy of `fmod.dll` or `libfmod.so` in the appropriate directory.

**Comment by vfrz** [comment]
> The FMOD audio implementation was always kind of an experiment, one which I eventually did away with when I realized that the license terms didn't allow me to distribute fmod.dll alongside Ultraviolet. That remains true as far as I'm aware, but given the recent pricing changes, I agree that I should probably revisit this in the near future.
> 
> Longer term, I want to look into an implementation based on OpenAL Soft, which has no cost. If I can make that work on all supported platforms, it will probably replace BASS as the default implementation.

I understand. I can't find recent information about redistribution of the fmod .dll/.so
OpenAL could be convenient but I actually had a really hard time using it a few time ago, good luck with that!

> I've pushed a new release to NuGet which includes the `Ultraviolet.FMOD` package, and I've made sure the package is no longer marked as deprecated. You should be able to find `FMODAudioPlugin` there. Please remember that, for licensing reasons, you'll need to provide your own copy of `fmod.dll` or `libfmod.so` in the appropriate directory.

Thanks for this.
