### ISSUE TITLE
Selecting text in a password box crashes

### ISSUE THREAD

**Issue by fireball87** [tlgkccampbell/ultraviolet#140]
When I highlight text in a password box, i will crash in password box OnQueryCursor as ```this.PART_Editor?.Cursor.Resource``` is null and therefore ```this.PART_Editor?.Cursor.Resource.Cursor``` is a null de-reference.

**Comment by tlgkccampbell** [comment]
Resolved in 2021.2.0.4548.

**Comment by fireball87** [comment]
Thanks
