### ISSUE TITLE
Nuget dependency issue.

### ISSUE THREAD

**Issue by fireball87** [tlgkccampbell/ultraviolet#142]
When updating to the latest version on nuget, it didn't grab the correct version of system.drawing.common or microsoft.codeanalysis.csharp as the packages requiring them do not claim to need versions as new as are actually needed.

**Comment by tlgkccampbell** [comment]
Which version of the packages were you upgrading to? There was a brief window where the published packages had invalid references, but this should be fixed in the newest versions.

**Comment by fireball87** [comment]
Newest as of when I had posted, 2021.5.0.4563.

**Comment by tlgkccampbell** [comment]
Can you try updating to 2021.5.0.4566 and see if that fixes it for you?

**Comment by fireball87** [comment]
That made the correct dependencies pull on update (after I had removed them from the project), so resolves the issue, thanks.
