### ISSUE TITLE
Project name not resolving to Assembly and Namespace

### ISSUE THREAD

**Issue by Predatorie** [tlgkccampbell/ultraviolet#22]
Hi,

I am just working through the examples with a project of my own and I noticed that when I create a new project via the the Ultraviolet Framework 1.3 Game template the name of the project does not resolve as I would have expected. The name of the assembly and namespace in my project is currently set  to SafeProjectName and not the name of my project. It's not a big deal obviously but I wanted to pass it on. I am using VS2015 Enterprise Update 1. If there is anything else you need let me know, thanks.

**Comment by tlgkccampbell** [comment]
Looks like an oversight in my build script that I missed during testing. Should be a pretty straightforward fix.

**Comment by tlgkccampbell** [comment]
Commit af5a4e9 addresses this issue. Will be fixed in the 1.3.2 installer.
