### ISSUE TITLE
Texture2D GetData missing?

### ISSUE THREAD

**Issue by Scellow** [tlgkccampbell/ultraviolet#26]
Hello

Im doing lot of texture manipulation, with MonoGame i can get/set texture data as array or color

How can i achieve the same with ultraviolet? I explored the whole source and can't find how to get the data of a Texture2D

**Comment by tlgkccampbell** [comment]
Ultraviolet maintains a stronger distinction between data on the CPU and GPU than some other libraries. A `Texture2D` is specifically for data which is loaded into GPU memory and used in a read-only fashion as a texture. For what you're doing, you want to either:

1) Use a `Surface2D` to load an image into CPU memory and manipulate it there, or
2) Use a `RenderTarget2D` if you're rendering a new image on the GPU

**Comment by tlgkccampbell** [comment]
It's worth noting, also, that you can _write_ to a `Texture2D` with the [`SetData()`](http://uv.twistedlogik.net/ultraviolet/reference/v1.3/html/Overload_TwistedLogik_Ultraviolet_Graphics_Texture2D_SetData.htm) method, you just can't get that data out again.

**Comment by Scellow** [comment]
Oh i didn't know about Surface2D, it should do the job then thanks :p

While you are here i have a question about Vector2, why X and Y setters are private?

**Comment by tlgkccampbell** [comment]
One of the design principles of Ultraviolet is: "value types should be immutable, unless there is a  measurable, significant performance benefit to making them mutable." The use of mutable value types in .NET is [generally considered bad form](http://stackoverflow.com/questions/441309/why-are-mutable-structs-evil).

Ultraviolet actually has `MutableVector2` and `MutableVector3` structures which it uses internally for various micro-optimizations, but in the majority of code, that sort of unsafe magic shouldn't be necessary. 

The mutability of the `VectorN` structures could potentially change in the future if I am presented with a sufficiently compelling benchmark.
