### ISSUE TITLE
Wiki needs an update on this sample.

### ISSUE THREAD

**Issue by chrhlnd** [tlgkccampbell/ultraviolet#3]
http://wiki.ultraviolet.tl/index.php?title=Sample_4_-_Content_Management

Forgot to mention changing the vertex buffer that is needed for the texture to have texcoords:

            this.vertexBuffer = VertexBuffer.Create<VertexPositionColorTexture>(3);
            this.vertexBuffer.SetData<VertexPositionColorTexture>(new[]{
                new VertexPositionColorTexture(new Vector3(0, 1, 0), Color.Red, new Vector2(0, 1)),
                new VertexPositionColorTexture(new Vector3(1, -1, 0), Color.Lime, new Vector2(1, 1)),
                new VertexPositionColorTexture(new Vector3(-1, -1, 0), Color.Blue, new Vector2(0, 0)),
            });

**Comment by tlgkccampbell** [comment]
I've made a note of this on the wiki. I also noticed that Sample 4 had a bug in it where it was allocating a vertex buffer of size 4 instead of 3, so I committed a fix for that as well.

Thanks!
