### ISSUE TITLE
StackOverflowExeption when trying to bind a property to TextBox

### ISSUE THREAD

**Issue by Scellow** [tlgkccampbell/ultraviolet#33]
Hello

Whenever i try to bind a property to a TextBox or PasswordBox it crash with a StackOverflowExeption
What i'm doing wrong?

Thanks!

OS: Windows 10 x64
Ultraviolet Version:  1.3.10.2035

```c#
using TheRoguer.Game.Managers;
using TwistedLogik.Ultraviolet.Content;
using TwistedLogik.Ultraviolet.UI;

namespace TheRoguer.Game.Screens
{
    public class LoginScreen : UIScreen
    {
        private readonly ScreenManager mScreenManager;
        private readonly ContentManager mContent;

        public LoginScreen(ContentManager content, ScreenManager screenManager) : base("Content/UI/Screens/LoginScreen", "LoginScreen", content)
        {
            mContent = content;
            mScreenManager = screenManager;
        }

        protected override object CreateViewModel(UIView view)
        {
            return new LoginViewModel(Ultraviolet);
        }
    }
}

using System;
using TwistedLogik.Ultraviolet;
using TwistedLogik.Ultraviolet.UI.Presentation;

namespace TheRoguer.Game.Screens
{
    public class LoginViewModel
    {
        public LoginViewModel(UltravioletContext uv)
        {
            mUv = uv;
            Mail = "testMail";
            Password = "testPass";
        }

        public void Login(DependencyObject element, ref RoutedEventData data)
        {
            Console.WriteLine($"Mail: {Mail} Pass: {Password}");
        }

        public string Mail { get; set; }
        public string Password { get; set; }

        private readonly UltravioletContext mUv;
    }
}
```
```xml
<?xml version="1.0" encoding="utf-8" ?>
<UIPanelDefinition>
  <View ViewModelType="TheRoguer.Game.Screens.LoginViewModel, TheRoguer.Game">

    <Image Source="#Global:Textures:DefaultUIBackground 0 0 1161 685" VerticalAlignment="Stretch" HorizontalAlignment="Stretch"/>

    <Grid VerticalAlignment="Stretch" HorizontalAlignment="Stretch">
      
      <Grid.ColumnDefinitions>
        <ColumnDefinition Width="128"/>
        <ColumnDefinition Width="*"/>
        <ColumnDefinition Width="128"/>
      </Grid.ColumnDefinitions>
      <Grid.RowDefinitions>
        <RowDefinition Height="128"/>
        <RowDefinition Height="*"/>
        <RowDefinition Height="128"/>
      </Grid.RowDefinitions>

      
      <StackPanel Grid.Column="1" Grid.Row="1" VerticalAlignment="Center" HorizontalAlignment="Center">
        
        <TextBox>{{Mail}}</TextBox>
        <PasswordBox></PasswordBox>
        
        <Button HorizontalAlignment="Center" Click="Login">Login</Button>
      
      </StackPanel>

    </Grid>
    
  </View>
</UIPanelDefinition>
```

**Comment by tlgkccampbell** [comment]
Looks like one of the refactorings I did to `TextEditor` a couple of releases ago has revealed a bug in the way the dependency property system compares strings. I think I have a fix; I'm going to see about pushing a hotfix release shortly.

**Comment by Scellow** [comment]
Awesome thanks a lot ! this is by far the best Game framework for C#, good work man!

**Comment by tlgkccampbell** [comment]
OK, I might have spoken a bit prematurely when I said the release would be out "shortly"... :smile: I found a related issue that I want to fix as well, but it's going to take me a little bit longer to do that properly. I should have something after I get home from work later tonight.

Thanks for the kind words, and also for bringing this issue to my attention.

**Comment by Scellow** [comment]
It's ok, i'll continue to learn more about the UI lib, it's just awesome, it's like WPF i like it a lot :D

**Comment by tlgkccampbell** [comment]
I've pushed out the 1.3.11 release, which should fix this issue. Note that as of 1.3.11 I'm no longer distributing an MSI installer, so if you've been using that, you'll need to switch your references over to NuGet.

Please read the release notes carefully; there have been some changes to the way routed event handlers work which became necessary as a result of the port to iOS, which may affect your code if you've been working in UPF.

I'll leave this issue open for the time being. Let me know if the update resolves it for you.

**Comment by Scellow** [comment]
Thanks a lot for this update!!

It's fixed for TextBox, but not for PasswordBox

I get this error: 

```
An unhandled exception of type 'System.AggregateException' occurred in TwistedLogik.Ultraviolet.UI.Presentation.dll

TheRoguer.Game: expression compiler error 1: Object reference not set to an instance of an object.
````

Maybe it has something to do with initializing the text(StringBuilder?) that is hidden by the dots in PasswordBox

**Comment by tlgkccampbell** [comment]
Ah, OK, that's actually intended, but there's a bug causing it not to display the correct error message, which I just fixed in the develop branch.

You can't bind directly to `PasswordBox` because it's not just a masked text box; it actually stores the string securely internally using `SecureString`. There's no property which exposes the raw password for two reasons: one, people could accidentally bind to it without realize the security implications, and two, it would have to allocate a new string every single time the property was accessed.

You can retrieve the raw password using the `PasswordBox` control's `GetPassword()` method. The `TextBox` control has an analogous method called `GetText()` which works the same way. Both of them have overloads which allow you to populate an instance of `StringBuilder` if you'd prefer to avoid allocating a bunch of unnecessary strings.

**Comment by Scellow** [comment]
It makes sense indeed! Well, we can now say that the issue is solved! :D

**Comment by tlgkccampbell** [comment]
:+1:
