### ISSUE TITLE
Still in development?

### ISSUE THREAD

**Issue by amerkoleci** [tlgkccampbell/ultraviolet#39]
Hi,
I saw your project and it looks very good, I'm working also on C# game engine with Vulkan and D3D12 support also, is this project still in development?

Thanks,
Amer

**Comment by tlgkccampbell** [comment]
Hi Amer,

Yes, Ultraviolet is still in development. Since the 1.3 branch is basically complete, I've been taking some time off to work on other things, but my intention is to get started on 1.4 probably at the beginning of the new year.

**Comment by tlgkccampbell** [comment]
It's been a bit slow going, but I have started work on the next release and expect to be ramping up more in the near future, so I'm going to close this issue.
