### ISSUE TITLE
What is best way to create ui?

### ISSUE THREAD

**Issue by RUSshy** [tlgkccampbell/ultraviolet#40]
Hi

What is best way to create UI for my game?

I have my GameScreen, should i create a HudScreen and open on top of GameScreen ?

or should i put all the HUD code in the GameScreen UI? 

How can i create custom controls, like Player HUD , Player Inventory etc

Do you have example game to show me how to correctly use the library, because i feel like i do thing really bad

Because when i add stuff in the XML like grid labels etc, then i can't click on my game, i mean i have my code to move, and it doesn't respond anymore

Thanks!

**Comment by RUSshy** [comment]
Oh and another question, how can i make UI without XML, just with spritebatch like batch.draw(button, x, y)

Like that it'll be faster and easier for me, is it possible?

**Comment by tlgkccampbell** [comment]
I hope to write some additional demos when I get back into working on 1.4, but for the time being the best example of UI code you're going to find is in Sample 13 - UPF (Advanced). There are a couple of custom controls defined in there.

With respect to input, you should always be able to query the states of the input devices from within `Update()` and respond accordingly, so if that's not working for you you're going to need to provide me with some more information. But if you're trying to handle input within the context of a UPF control, you need to understand how routed events flow through the visual tree, and make sure that your handlers are somewhere along the correct route, for example on the root element of the view.

If you're having trouble figuring out which properties/events are valid for a given control, I would recommend checking out the [reference documentation](http://uv.twistedlogik.net/ultraviolet/reference/v1.3/html/N_TwistedLogik_Ultraviolet_UI_Presentation_Controls.htm) for the built-in controls.

**Comment by RUSshy** [comment]
Ok i will try to learn  how to make new control with the sample 13 thanks

Also how can i check if nothing is focus, like i don't want my character to attack if i click on ui ?

**Comment by tlgkccampbell** [comment]
There's an `ElementWithFocus` property defined on `PresentationFoundationView` which you can check. If your code is inside of a UPF control, you can access this pretty easily:

    var focused = this.View.ElementWithFocus;

If your code is in a `UIScreen` you need to put in a bit of extra work to get the view reference:

```
using TwistedLogik.Ultraviolet.UI.Presentation;

// ...

var view = (PresentationFoundationView)this.View;
var focused = view.ElementWithFocus;
```

Of course, if you make your main game window a UPF control, then it will only receive input events if it (or one of its descendants) has focus.

**Comment by RUSshy** [comment]
I already tried with View.ElementWithFocus but then it is stuck because even if i click outside something like TextBox it keep focused

My code is in my game screen GameScreen : UIScreen

**Comment by RUSshy** [comment]
![Image](http://i.imgur.com/Vy9D38t.pngg)
and my xml



```xml
<?xml version="1.0" encoding="utf-8"?>
<UIPanelDefinition>
  <View ViewModelType="MyProject.Game, MyProject.Game">


    <Grid Name="GameView" Focusable="true" HorizontalAlignment="Stretch" VerticalAlignment="Stretch">


      <StackPanel Orientation="Vertical" VerticalAlignment="Top" HorizontalAlignment="Left"  Diagnostics.DrawVisualBounds="true" Diagnostics.DrawVisualBoundsColor="Red">
        <TextBlock>{{Debug}}</TextBlock>
        <TextBlock>{{Message}}</TextBlock>
        <Button>Test</Button>
      </StackPanel>


      <StackPanel Orientation="Vertical" VerticalAlignment="Bottom" HorizontalAlignment="Left"  Diagnostics.DrawVisualBounds="true" Diagnostics.DrawVisualBoundsColor="Blue">
         <TextBox Name="ChatInput" VerticalAlignment="Bottom">THIS IS A TEXT BOX</TextBox>
      </StackPanel>


    </Grid>

  </View>
</UIPanelDefinition>
```

**Comment by tlgkccampbell** [comment]
Sorry, I forgot...

You can put a `MouseClick` handler in your `GameView` element and have it reset focus for the view:

```
public void HandleMouseClick(DependencyObject dobj, MouseDevice device, MouseButton button, RoutedEventData data)
{
    var view = ((UIElement)dobj).View;
    var focused = ((UIElement)dobj).View.ElementWithFocus;
    if (focused != null)
    {
        view.BlurElement(focused);
    }
}
```

**Comment by RUSshy** [comment]
Now as soon as i click on textbox it unfocus instantly xD

This seems confusing to have the right implementation

**Comment by tlgkccampbell** [comment]
I've made a note to add some additional examples and documentation around UI creation in the next major release.

**Comment by RUSshy** [comment]
ty!

I think i understand a bit better now the ui because i put on pause my game and i learned WPF, now i find it easy to create with XML, but it's not 100% the same, sometimes ultraviolet use different name

**Comment by RUSshy** [comment]
also one feature request: to be able to reload the ui, so i dont have to restart game to see just one change xD that would be awesome :p
