### ISSUE TITLE
Can't remove border from scroll viewer

### ISSUE THREAD

**Issue by RUSshy** [tlgkccampbell/ultraviolet#44]
Hello

I can't remove the outline border from the scroll viewer, i tried to set border-thickness: 0; in the uvss document but it is still there, so i guess there is something missing that dont register that setting ?

**Comment by tlgkccampbell** [comment]
Can you post the UVSS and UVML that you're using? I'm pretty sure this works in the default UI styles.

**Comment by RUSshy** [comment]
i am using default UVSS http://pastebin.com/4neKHS7y

And here the xml:  http://pastebin.com/9JauDiV3

**Comment by RUSshy** [comment]
![mygame](https://cloud.githubusercontent.com/assets/18348637/22174629/74291d4e-dfe3-11e6-9251-a885fefd78af.png)

**Comment by tlgkccampbell** [comment]
Adding the following to my styles does the trick for me:

```css
ScrollViewer! >> Border!
{
	border-thickness: 0;
}
```

This is how the default style sheet removes the border from the scroll viewers inside of, for example, text boxes. Note that the above will apply to every scroll viewer, which is probably not what you want, but you can limit it to a specific element easily enough:

```css
#MyElement > ScrollViewer! >> Border!
{
	border-thickness: 0;
}
```

Note the difference between the `>` and `>>` operators. The former (`>`) is the "descendant" operator, while the latter (`>>`) is the "immediate visual child" operator. So this selector means "apply this rule to a `Border` which is the immediate visual child of a `ScrollViewer` which is somewhere inside the visual tree of an element named `MyElement`".

Knowing that the `Border` is an immediate child of the `ScrollViewer` requires knowledge of the control's layout. You can find the layout definitions for all of the built-in controls [here](https://github.com/tlgkccampbell/ultraviolet/tree/develop/TwistedLogik.Ultraviolet.UI.Presentation_Desktop/Controls).

**Comment by RUSshy** [comment]
The 1st code works fine, but the 2nd when i put the name, or even with Class, it doesn't work, ill try more thing, but ty i think ill keep the 1st since i don't think i'll need border on scroll view
