### ISSUE TITLE
How to generate TextureAtlas into a file directly ?

### ISSUE THREAD

**Issue by RUSshy** [tlgkccampbell/ultraviolet#50]
Hello

Is there a way to generate a TextureAtlas into a file ?

Because right now i can only generate TextureAtlas onto memory at runtime, but it takes more than 1 minutes because i load a lot of sprites :/

**Comment by tlgkccampbell** [comment]
If you [preprocess](https://github.com/tlgkccampbell/ultraviolet/wiki/Content-preprocessing) your `TextureAtlas` asset, the file that it writes out to disk will contain the final texture and all of the cell position data, which should load substantially faster. Is that what you mean?

**Comment by RUSshy** [comment]
I tried this, but it generate just  a atlas.uvc file, but when i load it then it is empty

App.ContentManager.Preprocess<TextureAtlas>("sprites/atlas.xml",false);
SpritesAtlas = App.ContentManager.Load<TextureAtlas>("sprites/atlas.uvc");

**Comment by RUSshy** [comment]
Oh no nvm it works :D :D thanks a lot :)
