### ISSUE TITLE
Chat channel

### ISSUE THREAD

**Issue by paezao** [tlgkccampbell/ultraviolet#51]
Hello,

Is there a official framework channel somewhere?

Cheers

**Comment by tlgkccampbell** [comment]
Hi paezao,

At present, pretty much all of the discussion around Ultraviolet takes place here on GitHub. So far there hasn't been much demand for anything like a chat channel, but as part of the next major release I'm planning on revamping the website/docs/etc., so maybe I'll look into setting up some kind of chat as well.

**Comment by paezao** [comment]
I'm testing the framework for a project and a chat channel would be awesome for basic questions and such. A gitter is really simple to setup.

**Comment by tlgkccampbell** [comment]
OK, I've created a [Gitter channel](https://gitter.im/ultraviolet-framework) for Ultraviolet. I'll keep an eye on it for anybody who wants to post any questions there.
