### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by Majirefy** [tlgkccampbell/ultraviolet#53]
Cannot reach website. Need some tutorials to get started.

**Comment by tlgkccampbell** [comment]
I'm making some modifications to the DNS servers that may result in the site being down for a while, but all of the information that was previously on wiki.ultraviolet.tl can now be found on the [GitHub wiki](https://github.com/tlgkccampbell/ultraviolet/wiki).

**Comment by Majirefy** [comment]
Thank!
Come from monogame. I found UltraViolet is much better designed for modern use, instead of old XNA API.
