### ISSUE TITLE
How to use in Visual Studio for Mac?

### ISSUE THREAD

**Issue by Majirefy** [tlgkccampbell/ultraviolet#54]
Is it possible to use UltraViolet in Visual Studio for Mac(Xamarin Studio)?

**Comment by tlgkccampbell** [comment]
Ultraviolet itself should work out of the box in Xamarin Studio. There's a solution specifically for macOS (in the `develop` branch it's `Source/Ultraviolet.macOS.sln`). I don't use macOS as my primary development platform, so if there are any problems, please let me know.

If you want to build the samples, you'll need to run `xbuild Ultraviolet.proj` at least once. Please see the *Building* sections of the README.md for more information.

**Comment by tlgkccampbell** [comment]
I should also note that if you want to just consume Ultraviolet as a library, then the easiest way to do it is through NuGet.  Just search for "Ultraviolet."  All of the Ultraviolet class libraries are available as separate packages, and there's a `TwistedLogik.Ultraviolet.Game.OSX` package which will set up the skeleton of a game project for you.
