### ISSUE TITLE
Change InputAction KeyboardBinding key/keys at runtime?

### ISSUE THREAD

**Issue by Spool5520** [tlgkccampbell/ultraviolet#56]
I've been looking through the source. It seems there is no way to change which key or keys that is binded to the InputAction? This would be incredibly useful for allowing users to choose which keys they want for any given KeyBind.

Perhaps something like 
`
public void ChangeActionKey(string actionName, Key key)
        {
            if(actions.ContainsKey(actionName))
            {
                actions[actionName].Primary = CreateKeyboardBinding(key);
            }
        }
`

obviously the implementation could be more safe. Or however you would like but having something like this would be incredibly useful. You may be able to do this already? Not sure.

**Comment by tlgkccampbell** [comment]
I'm not sure what you mean. The `Primary` and `Secondary` properties on `InputAction` already have public setters. Using Sample 2 as an example, you should be able to do:

```csharp
Actions.Instance.ExitApplication.Primary = new KeyboardInputBinding(Ultraviolet, Key.Whatever);
```

I don't think there's a way to access the actions by name through the `InputActionCollection` class, but the expectation is that you're going to be exposing them through your own class, as is done in the samples. It might be worth adding such a thing, though.

**Comment by Spool5520** [comment]
Oh sorry, my mistake. That makes perfect sense. Ill close the issue. Thanks for the response.
