### ISSUE TITLE
Portable dependency

### ISSUE THREAD

**Issue by loodakrawa** [tlgkccampbell/ultraviolet#58]
Hi,

Any plans to add a portable dependency?

I'm the author of the [SpriterDotNet library](https://github.com/loodakrawa/SpriterDotNet) and I plan to add UV as a renderer in addition to MonoGame. Also, I'd like to create a portable library and publish it to NuGet (similar to what I've done for [MonoGame](https://www.nuget.org/packages/SpriterDotNet.MonoGame/)) but I can't do it at the moment since there's no portable UV dependency.

Btw, great work with UV!

Cheers

**Comment by tlgkccampbell** [comment]
Portable Class Libraries are unlikely to happen, given that PCLs aren't really supported by Microsoft anymore anyway, but support for .NET Standard probably will at some point. I haven't done much research into how much effort would be required, or if .NET Standard even supports all of the features I require at this point, so I can't give a time frame for when it might happen.

Thanks for your kind words. 😄

**Comment by tlgkccampbell** [comment]
I spent a little bit of time experimenting with things today to get an idea of what would be required to support .NET Standard. There are some things I can do immediately to make the transition easier, and those will probably go in the next major release of Ultraviolet.

However, I think I'm going to be sticking with my original plan of waiting for the release of .NET Standard 2.0 before I port Ultraviolet. Given how big of a change it looks like it's going to be between 1.0 and 2.0, it doesn't seem sensible to go to the effort of updating my entire codebase right now. 

Once .NET Standard 2.0 is out and supported by all of Ultraviolet's key platforms (Windows, Linux, macOS, iOS, Android), I will almost certainly be releasing a compatible version of Ultraviolet soon thereafter.

**Comment by loodakrawa** [comment]
To be honest I haven't even considered .NET Standard yet but after taking a look it seems that the 2.0 version will come soonish and hopefully will allow to properly develop cross-platform libraries. 

Anyway, waiting for it makes perfect sense. Thanks for looking into it.

**Comment by tlgkccampbell** [comment]
I know it's been a while, but I'm working on .NET Standard 2.0 support now in the `netstandard` feature branch. Everything seems to be coming along well, so I'll be finishing that up today and tomorrow and the new assemblies will be included in the 2018.01 release.

**Comment by tlgkccampbell** [comment]
.NET Framework 2.0 and .NET Core 2.0 support is complete and has been merged into the 2018.01 development branch. When that release goes out, the appropriate NuGet packages will also be made available.
