### ISSUE TITLE
vertexBuffer.SetData from XNA to UV

### ISSUE THREAD

**Issue by RUSshy** [tlgkccampbell/ultraviolet#59]
Hi,

I try to port some feature of nez (the UI for example, it is libgdx port wich i prefer, it is easier), but it looks like the api is different for DrawIndexedPrimitives 

For example:

https://github.com/prime31/Nez/blob/master/Nez.Portable/Graphics/Batcher/Batcher.cs#L1031

I can't find similar for UV, do you have ideas ?

**Comment by RUSshy** [comment]
Oops actually it is this one:

https://github.com/prime31/Nez/blob/master/Nez.Portable/Graphics/Batcher/Batcher.cs#L951

_vertexBuffer.SetData( 0, _vertexInfo, 0, _numSprites, VertexPositionColorTexture4.realStride, SetDataOptions.None );

**Comment by tlgkccampbell** [comment]
`DrawIndexedPrimitives()` is a method on `IUltravioletGraphics` and `SetData()` is a method on `VertexBuffer`. What are you missing, exactly?

**Comment by RUSshy** [comment]
ok i think i found, i needed to use a GeometryStream!

**Comment by RUSshy** [comment]
hmm i converted it but i draw nothing on my screen, i think it is because of matrix i saw one talking in the issue tracker here but i know nothing about that, do you have an idea? here my what i have 

https://pastebin.com/MkSpJxJ7
