### ISSUE TITLE
Embed primary Ultraviolet Window into Form controls?

### ISSUE THREAD

**Issue by SPGardebiter** [tlgkccampbell/ultraviolet#60]
Hello.
I'm looking for a way to embed a Ultraviolet window into a windows form control because I'm writing a small editor for my application. Is there any simple way to do it?
I've been trying to look into the source code but it looks like the corresponding class is missing (I'm refering to "TwistedLogik.Ultraviolet.OpenGL.Platform.OpenGLUltravioletWindow".)

I didn't actually expect this code to work but I guess this is the usual way you would do it with an actual control:

```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using TwistedLogik.Ultraviolet;

namespace Test
{
    public partial class Editor : Form
    {
        public Editor()
        {
            InitializeComponent();

            var context = UltravioletContext.DemandCurrent();
            var window = context.GetPlatform().Windows.GetPrimary();
            splitContainerGame.Panel1.Controls.Add((System.Windows.Forms.Control)window);
        }
    }
}
```

**Comment by tlgkccampbell** [comment]
Yes, Ultraviolet supports this directly. I am about to board an airplane, so I can't give you a detailed write-up at the moment, but please take a look at the UltravioletTool project in the master branch. It uses the TwistedLogik.Ultraviolet.WindowsForms library, which provides both an UltravioletForm and an UltravioletPanel class from which you can inherit. 

If you're still having trouble, I'll do my best to help out tomorrow after I'm done traveling.

**Comment by tlgkccampbell** [comment]
Were you able to get this working?

**Comment by SPGardebiter** [comment]
Oh, hello.
Thanks for your quick answer and sorry for the silence on my part. I've been able to take a look at the UltravioletTool project but I got busy with work and some health related issues.
From what I've observed it isn't possible to just add the window to an UltravioletApplication class, I would need to create a UltravioletContext for the actual form, which means I have to create a new class, correct? I'm asking this because of the way I tend to design my code. At the moment my GameController is just a subclass of the UltravioletApplication class, if I would use a second class which is very simular but is a subclass of another class, then I would need to create a static class which contains the code my current GameController contains because multiple inheritance is not an option in C#. Am I correct?

**Comment by tlgkccampbell** [comment]
Yes, in a Windows Forms application, the `UltravioletForm` class serves as the Ultraviolet host (i..e, it replaces the `UltravioletApplication` class). There are other scenarios where this is the case as well: for example, if you're building your project for Android, you need to use `UltravioletActivity`. For this reason, shared library code generally shouldn't really make any references to any of the Ultraviolet host classes.

**Comment by SPGardebiter** [comment]
Hmmm, I see. So the way it's designed in UV is probably already the best way one could do it.
Many thanks for your time, I think I will be able to implement this change, it might take some time though, as I need to finish some other things first.

**Comment by tlgkccampbell** [comment]
Sure thing. Let me know if you run into any issues.

**Comment by SPGardebiter** [comment]
Hello.
I can't get it working. I can't find a NuGet Package for "UltravioletTool". I could compile it myself but I'm stuck with Visual Studio 2013 because of the new license model used for newer versions, so I am pretty much stuck at this point.

**Comment by tlgkccampbell** [comment]
Looking at it again, apparently I never bothered to make a NuGet package for the `UltravioletTool` project. I can get that fixed in the next couple of days when I have some time to look at it.

**Comment by tlgkccampbell** [comment]
Sorry for taking so long to get back to this. I recently moved and started a new job, so the amount of time I've been able to invest in Ultraviolet has been very limited for the past several months.

I just pushed a new build to the NuGet servers. This build includes two new packages:

* `TwistedLogik.Ultraviolet.WindowsForms` - the library which defines the Windows Forms controls
* `TwistedLogik.Ultraviolet.Game.WindowsForms` - a simple skeleton project

Be aware that it may take a bit of time for these packages to appear in the NuGet index.

Please let me know if you still have issues.
