### ISSUE TITLE
Missing DLLs in sample Dependencies folder

### ISSUE THREAD

**Issue by RUSshy** [tlgkccampbell/ultraviolet#61]
Hi,

I wanted setup samples for a friend, but i can't build, it misses DLLs from Samples/Dependencies folder

Is there automated way or i have o put builded dll into that folder ?

**Comment by tlgkccampbell** [comment]
From a VS Developer Command Prompt, run `msbuild Ultraviolet.proj` in the repository's root directory.

**Comment by tlgkccampbell** [comment]
I haven't heard back from you on this, so I'm assuming the problem has been resolved. Let me know if that isn't the case.

**Comment by RUSshy** [comment]
Hey, yes this is fixed, ty!
