### ISSUE TITLE
Default window color

### ISSUE THREAD

**Issue by Scellow** [tlgkccampbell/ultraviolet#66]
By default the window is plain white but i'd like to be able to choose a custom color

I checked SDL doc and all i could find is something related to when the SDL2_Renderer is created but you don't seems to rely on it so i'm a bit lost

**Comment by tlgkccampbell** [comment]
I'm not entirely sure what you mean by this. By default the backbuffer is cleared to cornflower blue, not white. And if you need it to be a different color, you can always clear it again using `IUltravioletGraphics.Clear()`.

**Comment by Scellow** [comment]
When the window is created it is all white https://i.imgur.com/roYjt1G.gifv

**Comment by tlgkccampbell** [comment]
Ah, I see. You can do two things to address this:

1. Hide the window until you've rendered at least one frame. 
  - You can make the main window start as hidden by setting `WindowIsVisible` to `false` when you create your Ultraviolet configuration object.
 - Call `Ultraviolet.GetPlatform().Windows.GetPrimary().Visible = true;` to make it visible again.

2. Reduce the amount of time it takes to render your first frame.
  - Loading all of your content assets can take a good chunk of time, and I'm guessing you're doing it synchronously (i.e. the easy way). Nothing is getting drawn while this happens.
  - See _Sample 10 - Asynchronous Content Loading_ for an example of how to load content asynchronously. This will allow you to render to the screen while simultaneously loading your game's assets.
  - Running in Release mode and use preprocessed assets should also reduce startup times.
