### ISSUE TITLE
Texture2D SetData ignore offset and count parameters

### ISSUE THREAD

**Issue by Scellow** [tlgkccampbell/ultraviolet#67]
https://github.com/tlgkccampbell/ultraviolet/blob/develop/Source/Ultraviolet.OpenGL/Shared/Graphics/OpenGLTexture2D.cs#L449

**Comment by tlgkccampbell** [comment]
This is very old code that was needlessly bloated with a bunch of functionality that was never being used, so I just ripped most of it out and rewrote what was left. The next release should fix this issue.
