### ISSUE TITLE
Is this the right engine for a game like this?

### ISSUE THREAD

**Issue by TheAwesomeGem** [tlgkccampbell/ultraviolet#69]
Basically I asked reddit on what engine to use to make a completely UI based game here: https://www.reddit.com/r/csharp/comments/7ptaj9/need_a_decent_gui_system_for_my_game/

Someone refereed me here. My question is. Is it stable enough to make a desktop game full of complex UI system? Thanks!

**Comment by tlgkccampbell** [comment]
Functionally speaking, Ultraviolet should do everything you asked for. If you know how to build something in WPF then almost none of UPF will be a surprise to you; it works in basically the same way and (most of) the major controls are (mostly) implemented. If you take a look at the reference documentation you can get a pretty good sense of what I mean.

I am fairly confident in the Framework's stability at this point. Obviously people do find bugs from time to time, but they're generally not show-stoppers. Now that I'm back from my hiatus, I'm aiming to put out a new release every month, so as long as bugs get reported they should get fixed quickly.

That said, I'm not aware of anyone who has used UPF to make applications with very large, very deeply-nested trees of controls, so what sort of performance you'd see in that scenario is a bit of an open question. The Presentation Foundation is implemented using a digest cycle simular to Angular, and every component is updated every frame, so there can be a lot of work to do. That said, the Foundation's performance is something I'm interested in and something I try to improve at least a little bit every time I look at it.

**Comment by tlgkccampbell** [comment]
I should add, since you brought it up in your Reddit post, that I also found WPF's system for styling controls to be a bit vexing. Ultraviolet uses a CSS-like language for styles.

**Comment by tlgkccampbell** [comment]
Thanks. And please let me know if you need any help with anything!
