### ISSUE TITLE
.net core package on nuget ?

### ISSUE THREAD

**Issue by RUSshy** [tlgkccampbell/ultraviolet#70]
Hi, i seen in your commit you added support for .net core, but i can't see on nuget, is it ready for it ?

**Comment by tlgkccampbell** [comment]
All of the latest library packages support .NET Standard 2.0, which is compatible with .NET Core 2.0. However, there's no "all-in-one" package like there is for other platforms, due to differences in how NuGet works.

**Comment by RUSshy** [comment]
Yes i tried to install the packages from nuget but i get this error on compile:

Unhandled Exception: System.TypeLoadException: Could not load type 'System.Drawing.Icon' from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

But System.Drawing doesn't exist for .net core

**Comment by tlgkccampbell** [comment]
It's possible that I screwed up the dependency chain in the new packages. It's supposed to be using `System.Drawing.Common` to provide that functionality on CoreCLR. I'll prioritize fixing it for the 2018.01 release.

**Comment by tlgkccampbell** [comment]
Well, it looks like the new NETCore shim package didn't get pushed to NuGet at all, so that probably isn't helping.

**Comment by tlgkccampbell** [comment]
Wait... I've already lost track of my own release schedule. 🤣 None of this has been released yet.

Those commits happened after 2017.12 was released. The NuGet packages with .NET Standard support haven't been published to NuGet yet. They'll become available after the 2018.01 release.

**Comment by RUSshy** [comment]
Oh ok xD ill compile from source then ty!

**Comment by tlgkccampbell** [comment]
My current recommendation is that you hold off on using Ultraviolet on .NET Core for the time being; I'm strongly considering holding back the NuGet packages when I release 2018.01. As I've continued work, it has become apparent that there are still some missing/incomplete APIs which result in things not working exactly right on all platforms.

Things should be better when .NET Core 2.1 is released, but I have no idea what the ETA is on that.

**Comment by hasali19** [comment]
Since .NET Core 2.1 has been released now, is there any update on this? I'd be interested to know what particular APIs are missing that are causing issues.

**Comment by tlgkccampbell** [comment]
It's on my radar, and I'll likely be looking into it once I have time to work on Ultraviolet again (in the next few weeks). There are a couple of pain points with the API, mainly the System.Drawing stuff, which should be resolved with either the new compatibility library or some other suitable .NET Core image handling library. As I recall, there's also some problems around correct DPI handling but I consider that lower priority.

**Comment by tlgkccampbell** [comment]
The new Windows Compatibility Pack seems to work, so barring any additional problems you can expect to see an official .NET Core 2.1 release of Ultraviolet as part of 2018.08.
