### ISSUE TITLE
Other Primitive types?

### ISSUE THREAD

**Issue by VoxlDavid** [tlgkccampbell/ultraviolet#73]
Are you going to add other primitive types? Right now the only ones available (as far as I know) are Line list, Line strip, Triangle list and Triangle strip. Are you going to add Triangle fan, Quad, etc?

**Comment by tlgkccampbell** [comment]
Probably not. Quads and triangle fans aren't well-supported across either APIs or the underlying hardware.

**Comment by VoxlDavid** [comment]
I see.. got what I wanted working with a triangle strip too so it's okay I guess :D
