### ISSUE TITLE
Using Lua files in content

### ISSUE THREAD

**Issue by VoxlDavid** [tlgkccampbell/ultraviolet#75]
Hey, I'm currently working on scripting for my engine and I'd like to know what type to supply in the manifest file for .lua files or plain text files. From checking your source code I know that the content Importer returns an array of strings, should it be ArrayOfString or something like that?

**Comment by tlgkccampbell** [comment]
Loading content in Ultraviolet is a two step process: the importer loads the raw file from disk and converts it into an intermediate type, and the processor converts the intermediate type into the type which is actually used by the engine. 

The built-in importer for `*.txt` files produces `System.String[]`, as you've already discovered. The built-in processor for `System.String[]` will produce an `IEnumerable<String>`, but there's no way to correctly represent generic types in the manifest XML, which is an oversight on my part. I'll look into fixing that in the 2018.2 release.

You can work around this by creating your own content processor that takes `System.String[]` and produces some non-generic wrapper type for the data. In that case, the type in the manifest would be the full, assembly-qualified name of the wrapper type, i.e. `My.Data.WrapperType, MyAssembly`.

You can register custom importers and processors by calling `Ultraviolet.GetContent().RegisterImportersAndProcessors()` and passing in the assembly which defines them.

To load `*.lua` files, you'd either need to create your own importer and register it as described above, or you'd need to tell Ultraviolet to use one of these existing importers for that extension. You can do that by calling `Ultraviolet.GetContent().Importers.RegisterImporter<TextContentImporter>("lua")`.

**Comment by VoxlDavid** [comment]
Would this be sufficient?

~~~ C#
namespace DefectEngine.Content {
    public class ScriptProcessor : ContentProcessor<String[], String> {
        public override string Process(ContentManager manager, IContentProcessorMetadata metadata, string[] input) {
            return string.Join("\n", input);
        }
    }
}
~~~

**Comment by tlgkccampbell** [comment]
You'll want to attach a `[ContentProcessor]` attribute to that class, but otherwise it looks like it should work.

A custom importer would let you avoid splitting the string apart just to join it back together again.

**Comment by VoxlDavid** [comment]
I see, thank you for your help :)

**Comment by VoxlDavid** [comment]
So this combination then?

~~~ C#
namespace DefectEngine.Content {
    [ContentImporter(".lua")]
    public class ScriptImporter : ContentImporter<String> {
        public override string Import(IContentImporterMetadata metadata, Stream stream) {
            using (var reader = new StreamReader(stream)) {
                return reader.ReadToEnd();
            }
        }
    }
}
~~~

and

~~~C#
namespace DefectEngine.Content {
    [ContentProcessor]
    public class ScriptProcessor : ContentProcessor<String, String> {
        public override string Process(ContentManager manager, IContentProcessorMetadata metadata, string input) {
            return input;
        }
    }
}
~~~

**Comment by tlgkccampbell** [comment]
That looks like it should do it.
