### ISSUE TITLE
3D ?

### ISSUE THREAD

**Issue by RUSshy** [tlgkccampbell/ultraviolet#76]
Hi,
When is 3D support added ?

Ty!

**Comment by tlgkccampbell** [comment]
I'm afraid the only answer I have for you is "eventually." I have a list of things that need to be done, and whenever I finish one of them I grab something else. I'm just one person. 😄

**Comment by RUSshy** [comment]
I copied monogame stuff, if you want to have same design as XNA i can clean it and send a pull request it is ok for you ? :D

**Comment by RUSshy** [comment]
But one problem there is no lightning yet and no animation yet

**Comment by tlgkccampbell** [comment]
I'm not sure I want to just copy MonoGame; one of the reasons I've been putting off 3D for so long is that I want to take the time to step back and do it in a way that makes sense for Ultraviolet.

Maybe you could put the work you've done into a separate NuGet package for people who need 3D in the meantime?

**Comment by RUSshy** [comment]
I never used nuget i don't know how to do that i think i'm just make git repo

**Comment by RUSshy** [comment]
do you think you can add 3d into ultraviolet in next update if i can pay ?
im strugling with 3D animation, this is so hard for me :(

**Comment by RUSshy** [comment]
Congrats on new job!
Ahhhh next is 3D ty!! i was trying for this last month but it's so hard i mean i follow different opengl tutorial but it is different and hard to translate to ultraviolet, and they are on c++ wich make it even harder for me
