### ISSUE TITLE
Build from source failed

### ISSUE THREAD

**Issue by VoxlDavid** [tlgkccampbell/ultraviolet#77]
Got this when trying to build from source (newest release 2018.1 or something)

I entered "msbuild Ultraviolet.proj"

Build FAILED.

"D:\ultraviolet-2018.01\Ultraviolet.proj" (default target) (1) ->
"D:\ultraviolet-2018.01\Source\Ultraviolet.Windows.sln" (default target) (2) ->
"D:\ultraviolet-2018.01\Source\UvDebug\Desktop\UvDebug.Desktop.csproj" (default target) (26) ->
(AfterBuild target) ->
  UvDebug : expression compiler error 1: Could not load file or assembly 'UV_CompiledExpressions\\NETStandard.Library.2
.0.1\\build\\netstandard2.0\\ref\\System.Runtime.InteropServices.dll' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047) [D:\ultraviolet-2018.01\Source\UvDebug\Desktop\UvDebug
.Desktop.csproj]
  D:\ultraviolet-2018.01\Source\UvDebug\Desktop\UvDebug.Desktop.csproj(317,5): error MSB3073: The command ""UvDebug.exe
" -resolve:content -compile:content -compile:expressions" exited with code 255.

**Comment by tlgkccampbell** [comment]
Ah, yes, I see the problem -- if you don't have the SDK installed, there's a bit of code that's supposed to use NuGet to download the necessary assemblies, but that seems not to be working correctly. I'll see if I can get that fixed here shortly.

**Comment by tlgkccampbell** [comment]
OK, I've just committed a change to the `develop` branch which should allow the compiler to work even on systems which don't have the 4.7.1 SDK installed (though I would still recommend that you install it). Let me know if you still have issues.

**Comment by VoxlDavid** [comment]
I got it to work now, thanks for your help!
