### ISSUE TITLE
Shader Problem ?

### ISSUE THREAD

**Issue by RUSshy** [tlgkccampbell/ultraviolet#79]
Hi, When i render model with BasicEffect it work, but when load the frag/vert manually it doesn't!

There is something wrong too, look

This work, model render
```c#
            _basicEffect.Projection = camera.projection;
            _basicEffect.View = camera.view;
            _basicEffect.World = _transform;
            
            _basicEffect.TextureEnabled = true;
            _basicEffect.Texture = texture;
            
            _basicEffect.VertexColorEnabled = true;
            _basicEffect.DiffuseColor = Color.White;
```

This work too, model render but without scaling!!, and is all white
```c#
            _basicEffect.Parameters["Projection"].SetValue(camera.projection);
            _basicEffect.Parameters["View"].SetValue(camera.view);
            _basicEffect.Parameters["World"].SetValue(_transform);
            
            _basicEffect.Parameters["Texture"].SetValue(texture);
            _basicEffect.Parameters["DiffuseColor"].SetValue(Color.White);
```

Now with shader loaded from xml:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<Effect>

    <!-- Parameters -->
    <Parameter>Texture</Parameter>
    <Parameter>DiffuseColor</Parameter>
    <Parameter>World</Parameter>
    <Parameter>View</Parameter>
    <Parameter>Projection</Parameter>
    <Parameter>DiffuseColor</Parameter>

    <Technique Name="Technique0">
        <Pass Name="Pass0">
            <VertexShader>test.vert</VertexShader>
            <FragmentShader>test.frag</FragmentShader>
        </Pass>
    </Technique>
    
</Effect>
```

```glsl
// vert
#version 140

uniform mat4 World;
uniform mat4 View;
uniform mat4 Projection;
uniform vec4 DiffuseColor;

in  vec4 uv_Position0;
in  vec4 uv_Color0;
in  vec2 uv_TextureCoordinate0;

out vec4 vColor;
out vec2 vTextureCoordinate;

void main()
{
	gl_Position        = Projection * View * World  * uv_Position0;
	vColor             = DiffuseColor * uv_Color0;
	vTextureCoordinate = uv_TextureCoordinate0;
}

//frag
#version 140

uniform sampler2D Texture;

in  vec4 vColor;
in  vec2 vTextureCoordinate;

out vec4 fColor;

void main()
{
	fColor = texture(Texture, vTextureCoordinate) * vColor;
}
```

And code:

```c#

// load
_effect = _content.Load<Effect>("Shader/test.xml");

// render
       _effect.Parameters["Projection"].SetValue(camera.projection);
            _effect.Parameters["View"].SetValue(camera.view);
            _effect.Parameters["World"].SetValue(_transform);
            
            _effect.Parameters["Texture"].SetValue(texture);
            _effect.Parameters["DiffuseColor"].SetValue(Color.White);

```

This doesn't work, nothing rendered, i took shaders from source 

BasicEffectColoredTextured vert and frag

**Comment by tlgkccampbell** [comment]
Your shaders look to be out of date. In 2017.12, the layout which Ultraviolet uses for matrices was changed. This was done to match the `System.Numerics.Vectors` library, which I would like to start using some day if Xamarin can ever figure out how to implement it correctly.

Anyway, this means that when you multiply a matrix and a vector, the vector needs to come first. Take a look at the [latest version](https://github.com/tlgkccampbell/ultraviolet/blob/develop/Source/Ultraviolet.OpenGL/Desktop/Resources/BasicEffectColoredTextured.vert) of that shader:

```glsl
gl_Position        = uv_Position0 * World * View * Projection;
vColor             = DiffuseColor * uv_Color0;
vTextureCoordinate = vec2(uv_TextureCoordinate0.x, 1.0 - uv_TextureCoordinate0.y);
```

Note also that texture v-coordinates have to be flipped in the shader now. Previously, this was done on the CPU, but it was changed in anticipation of the fact that I may eventually want to support platforms other than OpenGL.

**Comment by tlgkccampbell** [comment]
By the way, loading effects was made somewhat simpler in 2018.01. Per the release notes:

- An instance of `Effect` can now be created by directly loading either a `.frag` or a `.vert` file. The content processor will automatically load the corresponding vertex or fragment shader, so long as both shader files have the same name. For example, if you load `foo.vert`, the resulting program will be comprised of `foo.vert` and `foo.frag`.
- Added the `#param` GLSL directive, with syntax `#param "uniform_name"`. When this directive appears in a shader file, it indicates to Ultraviolet that an effect parameter needs to be created for the specified shader uniform. If the uniform cannot be located at runtime, Ultraviolet will throw an exception indicating that it was optimized out.

**Comment by RUSshy** [comment]
I got it to work thanks !!!
