### ISSUE TITLE
Depth problem

### ISSUE THREAD

**Issue by RUSshy** [tlgkccampbell/ultraviolet#80]
Hi, i try to render decal but sometime there is depth problem, transparency block behind object : 
https://pasteboard.co/HaPnhKY.png

```c#
render decal:            
            effect.Parameters["Projection"].SetValue(camera.projection);
            effect.Parameters["View"].SetValue(camera.view);
            effect.Parameters["World"].SetValue(transform);
            
            effect.Parameters["Texture"].SetValue(_tex);
            effect.Parameters["DiffuseColor"].SetValue(Color.White);

            foreach (EffectPass pass in effect.CurrentTechnique.Passes)
            {
                pass.Apply();
                device.SetTexture(0, _tex);
                device.SetDepthStencilState(DepthStencilState.DepthRead);
                device.SetRasterizerState(RasterizerState.CullClockwise);
                device.SetSamplerState(0, SamplerState.PointClamp);
                device.SetGeometryStream(_geometryStream);
                device.DrawPrimitives(PrimitiveType.TriangleList, 0, 2);
            }

render model:
   var texture = model.material.texture;
            effect.Parameters["Projection"].SetValue(camera.projection);
            effect.Parameters["View"].SetValue(camera.view);
            effect.Parameters["World"].SetValue(_transform);
            
            effect.Parameters["Texture"].SetValue(texture);
            effect.Parameters["DiffuseColor"].SetValue(Color.White);

            foreach (var pass in effect.CurrentTechnique.Passes)
            {
                pass.Apply();

                device.SetTexture(0, texture);

                device.SetDepthStencilState(DepthStencilState.DepthRead);
                device.SetRasterizerState(RasterizerState.CullClockwise);
                device.SetSamplerState(0, SamplerState.PointClamp);
                device.SetGeometryStream(model.stream);

                device.DrawPrimitives(PrimitiveType.TriangleList, 0, model.buffer.VertexCount / 3);
            }
```
Do you have idea what is going on ? i'm stuck on this

**Comment by tlgkccampbell** [comment]
A couple of thoughts:

1. How are you creating your projection matrix? What values are you using for zNear and zFar?
2. Try increasing the resolution of the default depth buffer. You can do this by setting the value of `BackBufferDepthSize` on `OpenGLUltravioletConfiguration` during context initialization. The default is 16; try 24.

**Comment by RUSshy** [comment]
```c#
        public float near = 0.1f;
        public float far  = 10000;

            var aspect = viewportWidth / viewportHeight;
            projection = Matrix.CreatePerspectiveFieldOfView(fieldOfView * Mathf.DEG_TO_RAD, aspect, near, far);
            view       = Matrix.CreateLookAt(position, position + direction, up);
            combined = projection * view;

```

**Comment by RUSshy** [comment]
i tried changing BackBufferDepthSize to 24 but it is still creating this sissue

**Comment by tlgkccampbell** [comment]
Try pushing your zNear a bit higher and your zFar a bit closer -- having a very small zNear can severely limit the precision of your depth buffer.

If that doesn't work, I'll find some time in the near future to try to reproduce this locally.

**Comment by RUSshy** [comment]
I tried 1 - 100 but it still same problem
It looks like it follow the draw order from the list

**Comment by tlgkccampbell** [comment]
I'll look into it and get back to you.

**Comment by RUSshy** [comment]
Ok ty! also is there a way to disable shader optimisation ?  for testing quickly i can have unused uniforms, and it crash because they are optimized out, is annoying

**Comment by RUSshy** [comment]
ok ty! also is there a way to disable shader optimisation ? for testing quick i have sometime unused uniform in vertex shader and it crash it is annoying

Unhandled Exception: System.InvalidOperationException: The expected effect parameter 'Time' does not have a corresponding shader uniform. Has it been optimized out?

**Comment by tlgkccampbell** [comment]
You might try adding `#pragma optimize(off)` to your GLSL, but I'm not sure it's guaranteed to work on all drivers. It's not something Ultraviolet has any control over.

**Comment by RUSshy** [comment]
I tried lot of things like changing blend state etc, but i can't fix that transparency problem, i don't know what do now :/

**Comment by tlgkccampbell** [comment]
I'm a little unclear on how the scene in your picture is being rendered. Is the blue stuff all one model, or multiple models? Are all of the 2D decals being rendered at once, and the 3D models rendered at once? What do your shaders look like?

It looks like you need to implement alpha testing in your fragment shader, i.e. something like

```glsl
uniform float ThresholdAlpha;

// ...

if (color.a < ThresholdAlpha)
    discard;
```

**Comment by RUSshy** [comment]
IT WORKS!!!! TY !!!!!!!

i spend lot of time and solution was easy x) TY TY!!!

```
#version 140

uniform sampler2D Texture;

in  vec4 vColor;
in  vec2 vTextureCoordinate;

out vec4 fColor;

void main()
{
        
    fColor = texture(Texture, vTextureCoordinate) * vColor;
	
    if (fColor.a < 0.5)
        discard;
}
```

**Comment by tlgkccampbell** [comment]
Glad to hear it.
