### ISSUE TITLE
Extract sample projects to a separate repo

### ISSUE THREAD

**Issue by orthoxerox** [tlgkccampbell/ultraviolet#82]
Hi.

It would probably be easier for the users of your framework to learn it if they could download a zip containing only the sample projects. The samples would have to reference the NuGet packages of Ultraviolet, of course.

**Comment by tlgkccampbell** [comment]
I used to distribute such a zip, but I stopped doing it, primarily out of laziness. That was also before Ultraviolet had NuGet packages, which complicated the situation considerably.

I can update my build server to produce such a zip without splitting things out into a separate repository, and I can attach the zip to Ultraviolet's releases on GitHub like I used to do. Do you think having a separate repository for the samples is valuable in and of itself?

**Comment by orthoxerox** [comment]
@tlgkccampbell I don't think a separate repo is that valuable, tbh, but a separate zip with samples would be great!

**Comment by tlgkccampbell** [comment]
Upon further consideration, I decided to go ahead and split the samples into their own repository, which can be found [here](https://github.com/tlgkccampbell/ultraviolet-samples). I'll be removing the samples from the main repository shortly, after I've updated my build server.
