### ISSUE TITLE
Consider placing links to Ultraviolet.Game.* packages in other NuGet packages' descriptions

### ISSUE THREAD

**Issue by orthoxerox** [tlgkccampbell/ultraviolet#84]
Something like "This package is a part of the Ultraviolet game engine framework and shouldn't be referenced directly unless you know what you are doing. To quickly create a new game project, reference one of the following packages instead: ..., ..., ..." would nudge people in the right direction.

**Comment by tlgkccampbell** [comment]
This is addressed by 517dc20d1aa847e76236b6659b654ad60c2cd635 and will be reflected in the 2018.04 release. Thanks for the suggestion.
