### ISSUE TITLE
Weird GPU usage

### ISSUE THREAD

**Issue by Scellow** [tlgkccampbell/ultraviolet#88]
I just recently noticed but GPU usage seems to be really high, to make sure it's nothing on my end, i used fresh source from develop branch on an empty project, GPU usage starts low  ~3-5% but few seconds later it jump to ~15-20%, that doesn't seems normal to me

```
            IsFixedTimeStep = false;
            SynchronizeWithVerticalRetrace = true;
```

I tried to check with NSIGHT but when i run the executable using it then  the GPU usage seems to stabilize at ~5%

Is VSYNC working properly ? how can i debug that ?
I'm not an expert so i'm not really sure where to check

**Comment by tlgkccampbell** [comment]
What tool are you using to see GPU usage?

**Comment by Scellow** [comment]
I checked the GPU usage with both the Windows Task Manager, and with GPUZ

I just tested with MonoGame and same behavior, so i think you are right!
