### ISSUE TITLE
Matrix[] passed to Effect seems to not send updated values

### ISSUE THREAD

**Issue by RUSshy** [tlgkccampbell/ultraviolet#95]
I have a Matrix[] to send to shader

When i first set values it works, but if i edit values of the array, then updated array is never sent

```c#
                for (int i = 0; i < n; i++)
                {
                    var invTransform = part.invBoneBindTransforms.values[i];
                    var node = part.invBoneBindTransforms.keys[i];
                    
                    part.bones[i] = invTransform * node.globalTransform;
                }

(...)

effect.Parameters["u_bones"].SetValue(nodePart.bones);
```

But if i create new instance of the array, then it works and send the updated values

Seems like cached value issue

**Comment by RUSshy** [comment]
Here https://github.com/tlgkccampbell/ultraviolet/blob/develop/Source/Ultraviolet.OpenGL/Shared/Graphics/OpenGLEffectParameterData.cs#L94

It compare the reference instead of the value of the array

**Comment by tlgkccampbell** [comment]
Yes, I see the problem, here. I can probably add some logic to forcibly invalidate the cache in this situation.

I'm going to be doing some work on Ultraviolet today, so this will be fixed in the next release.

**Comment by tlgkccampbell** [comment]
Fix has been merged to `develop`. Moving forward, calling `SetValue()` with any array type will always cause the array to be re-uploaded to the graphics device, regardless of it content.
