### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by stigzler** [tlgkccampbell/ultraviolet#99]
Hi - the wiki references samples, saying they're in the repo, but I can't find them. Are they still available?

**Comment by tlgkccampbell** [comment]
I've updated the wiki to reflect the new location of the samples. Thanks for reporting this error.

**Comment by stigzler** [comment]
> var data = new Color[128 * 128]; Array.Fill(data, Color.Red); _texture = Texture2D.CreateTexture(128,128); _texture.SetData(data); _batch = SpriteBatch.Create();

Sorry, I know this is closed, but struggling with RUSshy's code. I'm converting it to vb.net and **Array.Fill** doesn't compile???

Also, how do I get the image displayed - you've commented it out. Can't find a way to message RUSshy directly.

**Comment by tlgkccampbell** [comment]
The `Array.Fill()` method only exists in .NET Core. If you're using .NET Framework you'll have to fill the array manually in a `for` loop.
